import { Tournament } from '@/types/tournament';

export const mockTournaments: Tournament[] = [
  {
    id: '1',
    name: 'Sunshine State Junior Classic',
    date: '2026-03-15',
    endDate: '2026-03-16',
    location: 'Orlando, FL',
    state: 'FL',
    courseName: 'Orange County National Golf Center',
    ageGroups: ['U14', 'U16', 'U18'],
    gender: 'Mixed',
    registrationDeadline: '2026-03-01',
    status: 'Open',
    entryFee: 150,
    description: 'Annual junior classic open to players across Florida and the Southeast.',
  },
  {
    id: '2',
    name: 'Lone Star Junior Open',
    date: '2026-04-05',
    endDate: '2026-04-06',
    location: 'Dallas, TX',
    state: 'TX',
    courseName: 'TPC Craig Ranch',
    ageGroups: ['U12', 'U14', 'U16', 'U18'],
    gender: 'Boys',
    registrationDeadline: '2026-03-22',
    status: 'Open',
    entryFee: 125,
    description: 'Premier boys junior tournament in the Dallas–Fort Worth area.',
  },
  {
    id: '3',
    name: 'Pacific Pines Girls Championship',
    date: '2026-04-18',
    endDate: '2026-04-19',
    location: 'San Diego, CA',
    state: 'CA',
    courseName: 'Torrey Pines Golf Course',
    ageGroups: ['U14', 'U16', 'U18'],
    gender: 'Girls',
    registrationDeadline: '2026-04-04',
    status: 'Upcoming',
    entryFee: 175,
    description: 'Prestigious girls-only championship held on the iconic Torrey Pines course.',
  },
  {
    id: '4',
    name: 'Midwest Junior Golf Series – Spring Opener',
    date: '2026-05-02',
    endDate: '2026-05-03',
    location: 'Chicago, IL',
    state: 'IL',
    courseName: 'Cog Hill Golf & Country Club',
    ageGroups: ['U10', 'U12', 'U14'],
    gender: 'Mixed',
    registrationDeadline: '2026-04-18',
    status: 'Upcoming',
    entryFee: 100,
    description: 'Spring kickoff event for younger juniors in the Midwest region.',
  },
  {
    id: '5',
    name: 'Carolina Cup Junior Invitational',
    date: '2026-03-08',
    endDate: '2026-03-09',
    location: 'Charlotte, NC',
    state: 'NC',
    courseName: 'Quail Hollow Club',
    ageGroups: ['U16', 'U18'],
    gender: 'Mixed',
    registrationDeadline: '2026-02-22',
    status: 'Closed',
    entryFee: 200,
    description: 'Invitation-only event for elite junior golfers in the Carolinas.',
  },
  {
    id: '6',
    name: 'Desert Junior Open',
    date: '2026-02-14',
    endDate: '2026-02-15',
    location: 'Scottsdale, AZ',
    state: 'AZ',
    courseName: 'TPC Scottsdale',
    ageGroups: ['U12', 'U14', 'U16', 'U18'],
    gender: 'Mixed',
    registrationDeadline: '2026-01-31',
    status: 'Completed',
    entryFee: 130,
    description: 'Early-season tournament in the Valley of the Sun.',
  },
];
